name: Deploy Lambda Function
on:
#  push:
#    branches: main
#  pull_request:
#    branches: main
  workflow_dispatch:

jobs:
  release:
    name: Deploy lambda function
    runs-on: [ ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
          role-duration-seconds: 1200
          role-session-name: MySessionName
      - name: zip Lambda Function
        run: |
          zip -r9 lambda.zip hello-world.py
      - name: Upload to S3
        run: aws s3 cp lambda.zip s3://testing-lambda-123231231231/lambda.zip
      - name: Update lambda function code
        run: aws lambda update-function-code --function-name arn:aws:lambda:ap-south-1:051723651593:function:paccar --s3-bucket testing-lambda-123231231231 --s3-key lambda.zip
      - name: Sleep for 5 seconds
        run: sleep 5s
        shell: bash
      - name: Release lambda function version
        run: aws lambda publish-version --function-name arn:aws:lambda:ap-south-1:051723651593:function:paccar --description Lambda-test
      #- name: AWS Deploy
      #  run: |
      #    aws lambda update-function-code --function-name arn:aws:lambda:ap-south-1:051723651593:function:paccar --zip-file fileb://lambda.zip
