name: Deploy Lambda Function V2
on:
  workflow_dispatch:

jobs:
  release:
    name: Deploy lambda function
    runs-on: [ ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: zip Lambda Function
        run: echo ${{ secrets.TITLE }} | base64
